---

- name: Create application directory
  file:
    path: "{{ application_directory }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}"

- action:
    module: ec2_instance_info
    region: eu-west-2
    filters:
      "tag:Name": back_office
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
  register: ec2_bo_info
  
- name: Copy docker-compose file
  template:
    src: templates/docker-compose.yml
    dest: "{{ application_directory }}/docker-compose.yml"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
  notify: Restart docker compose

- name: Pull docker image API madu
  docker_image:
    pull: yes
    name: "{{ application_api_image }}:{{ application_api_tag }}"
    force_source: yes
  notify: Restart docker compose

- name: Start docker compose
  docker_compose:
    project_src: "{{ application_directory }}"