version: "3"
services:
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
      - data:/data/db

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo

  api:
    image: node:alpine
    restart: always
    working_dir: /app
    depends_on:
      - prisma
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    environment:
      PRISMA_SECRET: "MadUgr0up7"
      PORT: 3000
      FRONT_URL: http://localhost
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      APP_SECRET: "${APP_SECRET}"
    entrypoint: /app/entrypoint.sh
    command: yarn dev

  bo:
    image: node:12
    restart: always
    working_dir: /app
    stdin_open: true
    volumes:
      - ./back-office:/app
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: http://localhost:3000
      PORT: 80
    entrypoint: /app/entrypoint.sh
    command: yarn start

volumes:
  mongo: ~
  data: ~
