---

- name: Insert fixtures in DB
  hosts: tag_component_api
  become: yes
  tasks:
  - name: Execute fixture insert script
    shell: "docker-compose exec api node src/fixtures.js"
    args:
      chdir: /home/ubuntu/app