version: "3"

services:
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "{{ MONGO_INITDB_ROOT_USERNAME }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ MONGO_INITDB_ROOT_PASSWORD }}"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
      - data:/data/db

volumes:
  mongo: ~
  data: ~
