version: '3'

services:
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "{{ mongo_initdb_root_username }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_initdb_root_password }}"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
      - data:/data/db

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "{{ application_prisma_port }}:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo

  api:
    image: "{{ application_api_image }}:{{ application_api_tag }}"
    restart: always
    working_dir: /app
    depends_on:
      - prisma
    ports:
      - "{{ application_api_port }}:3000"
    environment:
      SECRET: "{{ api_secret }}"
      PORT: 3000
    entrypoint: /app/entrypoint.sh
    command: yarn start

  bo:
    image: "{{ application_backoffice_image }}:{{ application_backoffice_tag }}"
    ports:
      - "{{ application_backoffice_port }}:80"

volumes:
  mongo: ~
  data: ~
