---

- name: Install common libs and packages
  hosts: tag_component_madu_app
  gather_facts: no
  become: yes
  roles:
    - { role: common, tags: ["common"] }
    - { role: geerlingguy.docker, tags: ["common"] }

- name: Build project
  hosts: local
  connection: local
  roles:
    - { role: build, tags: ["build", "deploy"] }

- name: Install web service
  hosts: tag_component_madu_app
  vars_files:
    - ./inventory/group_vars/vault.yml
  become: yes
  roles:
    - { role: deploy, tags: ["deploy", "ci"] }