name: Master

on: 
  push:
    branches:
      - master
      - scalability
      - 0-get-elb-and-ec2-url

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Export Docker Hub credentials
        uses: ./.github/actions/setup-and-run
        with:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          CMD: |
            echo "::set-env name=DOCKER_USERNAME::$DOCKER_USERNAME" &&
            echo "::set-env name=DOCKER_PASSWORD::$DOCKER_PASSWORD" &&
            echo "::set-env name=REACT_APP_API_URL::http://elb-1509450197.eu-west-2.elb.amazonaws.com"

      - name: Build Api image
        uses: docker/build-push-action@v1
        with:
          path: ./api
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/madu_api
          tags: latest

      - name: Build Back-office image
        uses: docker/build-push-action@v1
        with:
          path: ./back-office
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/madu_back-office
          build_args: REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}
          tags: latest

      - name: Build App image
        uses: docker/build-push-action@v1
        with:
          path: ./app
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/madu_app-web
          build_args: REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}
          tags: latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy with Ansible playbook 
        uses: ./.github/actions/setup-and-run
        with:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          CMD: |
            ansible-playbook -i inventory/ec2.py staging.yml --tags deploy -u ubuntu --key ~/id_rsa
            