name: Master

on: 
  push:
    branches:
      - 0-get-elb-and-ec2-url

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test 
        uses: ./.github/actions/setup-and-run
        with:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          CMD: |
            ansible-playbook get_elb_dns.yml -i inventory/hosts &&
            cat elb_api_dns.txt &&
            echo "::set-env name=REACT_APP_API_URL::$(cat elb_api_dns.txt)"